# Generated by Django 2.2.16 on 2022-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220705_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categorygenrebase_ptr',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='categorygenrebase_ptr',
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoryGenreBase',
        ),
    ]
